package com.gottmusig.gottmusig.model.wowhead;

public enum ClassSpec {

	DEATH_KNIGHT_ANY(Classes.DEATH_KNIGHT),
	DEATH_KNIGHT_BLOOD(250),
	DEATH_KNIGHT_FROST(251),
	DEATH_KNIGHT_UNHOLY(252),
	
	DEMON_HUNTER_ANY(Classes.DEMON_HUNTER),
	DEAMON_HUNTER_HAVOC(577),
	DEAMON_HUNTER_VENEGEANCE(581),
	
	DRUIDE_ANY(Classes.DRUID),
	DRUIDE_BALANCE(102),
	DRUIDE_FERAL(103),
	DRUIDE_GUARDIAN(104),
	DRUIDE_RESTORATION(105),
	
	HUNTER_ANY(Classes.HUNTER),
	HUNTER_BEAST_MASTERY(253),
	HUNTER_MARKSMANSHIP(254),
	HUNTER_SURVIVAL(255),
	
	MAGE_ANY(Classes.MAGE),
	MAGE_ARCANE(62),
	MAGE_FIRE(63),
	MAGE_FROST(64),

	MONK_ANY(Classes.MAGE),
	MONK_BREWMASTER(268),
	MONK_WINDWALKER(269),
	MONK_MISTWEAVER(270),
	
	PALADIN_ANY(Classes.PALADIN),
	PLALADIN_HOLY(65),
	PALADIN_PROTECTION(66),
	PALADIN_RETRIBUTION(70),
	
	PRIEST_ANY(Classes.PALADIN),
	PRIEST_DISCIPLINE(256),
	PRIEST_HOLY(257),
	PRIEST_SHADOW(258),
	
	ROUGE_ANY(Classes.ROGUE),
	ROUGE_ASSASSINATION(259),
	ROUGE_OUTLAW(260),
	ROUGE_SUBTLETY(261),
	
	SHAMAN_ANY(Classes.SHAMAN),
	SHAMAN_ELEMENTAL(262),
	SHAMAN_ENHANCEMENT(263),
	SHAMAN_RESTORATION(264),
	
	WARLOCK_ANY(Classes.WARLOCK),
	WARLOCK_AFFLICTION(265),
	WARLOCK_DEMONOLOGY(266),
	WARLOCK_RESTORATION(267),
	
	WARRIOR_ANY(Classes.WARRIOR),
	WARRIOR_ARMS(71),
	WARRIOR_FURY(72),
	WARRIOR_PROTECTION(73);

	private int id;

	private ClassSpec(int id){
		this.id = id;
	}
	
	private ClassSpec(Classes wowClass){
		this.id = wowClass.getID();
	}
	
	public Filters getFilter(){
		Filters specFilter = Filters.LOOT_SPECIALIZATION;
		Filters.LOOT_SPECIALIZATION.setSpec(this);
		return specFilter;
	}
	
	public int getId(){
		return id;
	}
	
}
