INSERT INTO wowclass (name)  VALUES ('Warrior'),
                                   ('Paladin'),
                                   ('Hunter'),
                                   ('Rogue'),
                                   ('Priest'),
                                   ('Death Knight'),
                                   ('Shaman'),
                                   ('Mage'),
                                   ('Warlock'),
                                   ('Monk'),
                                   ('Druid'),
                                   ('Demon Hunter');

INSERT INTO classspecification (name, WOWClass_id) VALUES ('Fury',(SELECT id FROM wowclass WHERE wowclass.name = 'Warrior')),
                                                          ('Arms',(SELECT id FROM wowclass WHERE wowclass.name = 'Warrior')),
                                                          ('Protection',(SELECT id FROM wowclass WHERE wowclass.name = 'Warrior')),
                                                          ('Holy',(SELECT id FROM wowclass WHERE wowclass.name = 'Paladin')),
                                                          ('Protection',(SELECT id FROM wowclass WHERE wowclass.name = 'Paladin')),
                                                          ('Retribution',(SELECT id FROM wowclass WHERE wowclass.name = 'Paladin')),
                                                          ('Beast Mastery',(SELECT id FROM wowclass WHERE wowclass.name = 'Hunter')),
                                                          ('Marksmanship',(SELECT id FROM wowclass WHERE wowclass.name = 'Hunter')),
                                                          ('Survival',(SELECT id FROM wowclass WHERE wowclass.name = 'Hunter')),
                                                          ('Assassination',(SELECT id FROM wowclass WHERE wowclass.name = 'Rogue')),
                                                          ('Outlaw',(SELECT id FROM wowclass WHERE wowclass.name = 'Rogue')),
                                                          ('Subtlety',(SELECT id FROM wowclass WHERE wowclass.name = 'Rogue')),
                                                          ('Holy',(SELECT id FROM wowclass WHERE wowclass.name = 'Priest')),
                                                          ('Shadow',(SELECT id FROM wowclass WHERE wowclass.name = 'Priest')),
                                                          ('Discipline',(SELECT id FROM wowclass WHERE wowclass.name = 'Priest')),
                                                          ('Blood',(SELECT id FROM wowclass WHERE wowclass.name = 'Death Knight')),
                                                          ('Frost',(SELECT id FROM wowclass WHERE wowclass.name = 'Death Knight')),
                                                          ('Unholy',(SELECT id FROM wowclass WHERE wowclass.name = 'Death Knight')),
                                                          ('Elemental',(SELECT id FROM wowclass WHERE wowclass.name = 'Shaman')),
                                                          ('Enhancement',(SELECT id FROM wowclass WHERE wowclass.name = 'Shaman')),
                                                          ('Restoration',(SELECT id FROM wowclass WHERE wowclass.name = 'Shaman')),
                                                          ('Frost',(SELECT id FROM wowclass WHERE wowclass.name = 'Mage')),
                                                          ('Arcane',(SELECT id FROM wowclass WHERE wowclass.name = 'Mage')),
                                                          ('Fire',(SELECT id FROM wowclass WHERE wowclass.name = 'Mage')),
                                                          ('Affliction',(SELECT id FROM wowclass WHERE wowclass.name = 'Warlock')),
                                                          ('Destruction',(SELECT id FROM wowclass WHERE wowclass.name = 'Warlock')),
                                                          ('Demonology',(SELECT id FROM wowclass WHERE wowclass.name = 'Warlock')),
                                                          ('Brewmaster',(SELECT id FROM wowclass WHERE wowclass.name = 'Monk')),
                                                          ('Windwalker',(SELECT id FROM wowclass WHERE wowclass.name = 'Monk')),
                                                          ('Mistweaver',(SELECT id FROM wowclass WHERE wowclass.name = 'Monk')),
                                                          ('Guardian',(SELECT id FROM wowclass WHERE wowclass.name = 'Druid')),
                                                          ('Balance',(SELECT id FROM wowclass WHERE wowclass.name = 'Druid')),
                                                          ('Feral',(SELECT id FROM wowclass WHERE wowclass.name = 'Druid')),
                                                          ('Restoration',(SELECT id FROM wowclass WHERE wowclass.name = 'Druid')),
                                                          ('Havoc',(SELECT id FROM wowclass WHERE wowclass.name = 'Demon Hunter')),
                                                          ('Vengeance',(SELECT id FROM wowclass WHERE wowclass.name = 'Demon Hunter'));

INSERT INTO specificationdps (dps, classSpecification_id) VALUES (0,(SELECT id FROM classspecification WHERE name = 'Fury')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Arms')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Protection' AND WOWClass_id = (SELECT id FROM wowclass WHERE wowclass.name = 'Warrior'))),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Holy' AND WOWClass_id = (SELECT id FROM wowclass WHERE wowclass.name = 'Paladin'))),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Protection')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Retribution')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Beast Mastery')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Marksmanship')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Survival')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Assassination')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Outlaw')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Subtlety')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Holy')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Shadow')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Discipline')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Blood')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Frost')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Unholy')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Elemental')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Enhancement')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Restoration'AND WOWClass_id = (SELECT id FROM wowclass WHERE wowclass.name = 'Shaman'))),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Frost')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Arcane')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Fire')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Affliction')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Destruction')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Demonology')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Brewmaster')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Windwalker')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Mistweaver')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Guardian')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Balance')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Feral')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Restoration')AND WOWClass_id = (SELECT id FROM wowclass WHERE wowclass.name = 'Druid')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Havoc')),
                                                                 (0,(SELECT id FROM classspecification WHERE name = 'Vengeance'));
